export const DEFAULT_RESPONSES: string[] = [
  'It is certain',
  'It is decidedly so',
  'Without a doubt',
  'Yes, definitely',
  'You may rely on it',
  'As I see it, yes',
  'Most likely',
  'Outlook good',
  'Yes',
  'Signs point to yes',
  'Reply hazy, try again',
  'Ask again later',
  'Better not tell you now',
  'Cannot predict now',
  'Concentrate and ask again',
  "Don't count on it",
  'My reply is no',
  'My sources say no',
  'Outlook not so good',
  'Very doubtful',
  'Be strong, but gentle. Be confident, but humble. Be tenacious, but flexible.',
  'Spend a bit of time each week thinking about the type of person you would like to be, and a bit of time each week thinking about the type of person that you are.',
  'Be a warrior - at war with complacency.',
  'It is more important what you do, than what you have.',
  'Be that friend who everyone knows they can count on.',
];
